declare const _default: {
    "zh-CN": {
        homeTitle: string;
        homeSubtitle: string;
        homeSubtitle2: string;
        getStarted: string;
        allegory: string;
        scrollDown: string;
        weBelieve: string;
        weBelieveDesc1: string;
        weBelieveDesc2: string;
        weBelieveDesc3: string;
        whatWeDo: string;
        whatWeDoDesc1: string;
        whatWeDoDesc2: string;
        advantage: string;
        box1Title: string;
        box1Desc: string;
        box2Title: string;
        box2Desc: string;
        box3Title: string;
        box3Desc: string;
        whatDesc1: string;
        whatDesc2: string;
        read4More: string;
        moreInfo: string;
    };
    "en-US": {
        homeTitle: string;
        homeSubtitle: string;
        homeSubtitle2: string;
        getStarted: string;
        allegory: string;
        scrollDown: string;
        weBelieve: string;
        weBelieveDesc1: string;
        weBelieveDesc2: string;
        weBelieveDesc3: string;
        whatWeDo: string;
        whatWeDoDesc1: string;
        whatWeDoDesc2: string;
        advantage: string;
        box1Title: string;
        box1Desc: string;
        box2Title: string;
        box2Desc: string;
        box3Title: string;
        box3Desc: string;
        whatDesc1: string;
        whatDesc2: string;
        read4More: string;
        moreInfo: string;
    };
};
export default _default;
